CREATE TABLE Meals (
    ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    Preparation NVARCHAR(500) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL,
    MealType NVARCHAR(20) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL,
    DayID INT NOT NULL
);

CREATE TABLE Ingredients (
    ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    Name NVARCHAR(50) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL,
    Quantity INT NOT NULL,
    MealID INT NOT NULL,
    FOREIGN KEY (MealID) REFERENCES Meals(ID)
);

CREATE TABLE DayMeals (
    Date DATE PRIMARY KEY,
    DayID INT
);
