# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: DietDisplay build and deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  buildAPI:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore DietDisplay.API 
    - name: Build
      run: dotnet build DietDisplay.API --no-restore
    - name: Restore dependencies for tests
      run: dotnet restore DietDisplay.API.Tests
    - name: Build Test
      run: dotnet build DietDisplay.API.Tests --no-restore
    - name: Test
      run: dotnet test DietDisplay.API.Tests --no-build --verbosity normal
    - name: Publish
      run: dotnet publish DietDisplay.API --no-restore -c Release -r win-x64 --no-self-contained
    - name: Archive API artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist-API
        path: DietDisplay.API/bin/Release/net7.0/win-x64/publish
        
  buildReact:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies and build React app
        run: |
          cd dietdisplay.web
          npm install
          npm run build
      - name: Run tests
        run: |
          cd dietdisplay.web
          npm test
      - name: Archive React artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-React
          path: dietdisplay.web/build
          
  deployAll:
        needs: [buildAPI, buildReact]
        runs-on: ubuntu-latest
        if: github.event_name == 'push' 
        steps:
        - name: Download API files
          uses: actions/download-artifact@v3
          with:
            name: dist-API
            path: shared_files
        - name: Download React files
          uses: actions/download-artifact@v3
          with:
            name: dist-React
            path: shared_files
        - name: Replace DefaultConnection in appsettings.json
          run: |
            sed -i "s/{secrets.DefaultConnection}/${{ secrets.DefaultConnection }}/" shared_files/appsettings.json
        - name: Upload  API via FTP
          uses: SamKirkland/FTP-Deploy-Action@v4.3.4
          with:
            server: ${{ secrets.FTP_HOST }}
            username: ${{ secrets.FTP_USERNAME }}
            password: ${{ secrets.FTP_PASSWORD }}
            local-dir: ./shared_files/
