# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master", "yaml-setup" ]
  pull_request:
    branches: [ "master", "yaml-setup" ]

env:
  DOTNET_ROOT: /path/to/dotnet

jobs:
  buildAPI:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
          
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore DietDisplay.API 
    - name: Build
      run: dotnet build DietDisplay.API --no-restore
    - name: Test
      run: dotnet test DietDisplay.API --no-build --verbosity normal
    - name: Archive API build
      uses: actions/upload-artifact@v3
      with:
        name: API-build
        path: DietDisplay.API
    
  deployAPI:
    needs: buildAPI
    runs-on: ubuntu-latest
    steps:
    - name: Download API build
      uses: actions/download-artifact@v3
      with:
        name: API-build
        path: DietDisplay.API
    - name: Restore dependencies
      run: dotnet restore DietDisplay.API 
    - name: Publish
      run: dotnet publish DietDisplay.API --no-restore -c Release -r win-x64 --self-contained true
    - name: Archive API artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist-API
        path: DietDisplay.API/bin/Release/net7.0/win-x64
    - name: ZIP published API
      run: zip -r API.zip DietDisplay.API/bin/Release/net7.0/win-x64
    - name: Upload ZIP with API via FTP
      run: |
        curl -T API.zip ftp://${{ secrets.FTP_HOST }}/ --user ${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}
    - name: Unzip API on the server
      run: |
        curl -O ftp://${{ secrets.FTP_HOST }}/API.zip --user ${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}
        unzip -j -o API.zip
        rm API.zip
    - name: Clean up
      run: |
        rm -r API.zip
