# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore DietDisplay.API 
    - name: Build
      run: dotnet build DietDisplay.API --no-restore
    - name: Test
      run: dotnet test DietDisplay.API --no-build --verbosity normal
    - name: Publish
      run: dotnet publish DietDisplay.API --no-restore -c Release -r win-x64 --self-contained true
    - name: Deploy API to Server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: DietDisplay.API/bin/Release/net7.0/win-x64/
