# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: DietDisplay

on:
  push:
    branches: [ "master", "yaml-setup" ]
  pull_request:
    branches: [ "master", "yaml-setup" ]

jobs:
  buildAndDeployAPI:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
          
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore DietDisplay.API 
    - name: Build
      run: dotnet build DietDisplay.API --no-restore
    - name: Test
      run: dotnet test DietDisplay.API --no-build --verbosity normal
    - name: Publish
      run: dotnet publish DietDisplay.API --no-restore -c Release -r win-x64 --no-self-contained
    - name: Upload  API via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./DietDisplay.API/bin/Release/net7.0/win-x64/publish/
    - name: Archive API artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist-API
        path: DietDisplay.API/bin/Release/net7.0/win-x64/publish
        
  buildAndDeployReact:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies and build React app
        run: |
          cd dietdisplay.web
          npm install
          npm run build
      - name: Run tests
        run: |
          cd dietdisplay.web
          npm test
      - name: Upload  API via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dietdisplay.web/build/
      - name: Archive React artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-React
          path: dietdisplay.web/build
